version: "3.8"

services:
  web:
    build: .
    container_name: social_web
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - db
      - redis
      - celery_worker

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: social_redis
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

volumes:
  db_data:
  redis_data:
