version: "3.8"

services:
  web:
    build: .
    container_name: social_web
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: social_redis
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
